main: com.zszf.bcNewYearPlugin.main
version: 0.0.1
name: bcNewYearPlugin
api-version: 1.19
commands:
  startparkour:
    description: "开始跑酷"
    aliases:
      - sparkour
    usage: "/startparkour"
  stopparkour:
    description: "停止跑酷"
    usage: "/stopparkout"